packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.49.2
  '@nx/devkit': 22.2.5
  '@nx/eslint-plugin': 22.2.5
  '@nx/jest': 22.2.5
  '@nx/js': 22.2.5
  '@nx/plugin': 22.2.5
  '@nx/workspace': 22.2.5
  '@remotion/cli': ^4.0.390
  '@remotion/eslint-config': ^4.0.390
  '@remotion/fonts': ^4.0.390
  '@remotion/google-fonts': ^4.0.390
  '@remotion/media-utils': ^4.0.390
  '@remotion/noise': ^4.0.390
  '@remotion/paths': ^4.0.390
  '@remotion/shapes': ^4.0.390
  '@remotion/tailwind-v4': ^4.0.390
  '@storm-software/build-tools': 0.151.19
  '@storm-software/cloudflare-tools': ^0.71.19
  '@storm-software/config': ^1.134.67
  '@storm-software/config-tools': ^1.188.67
  '@storm-software/cspell': ^0.45.66
  '@storm-software/esbuild': ^0.53.67
  '@storm-software/eslint': ^0.169.68
  '@storm-software/git-tools': ^2.124.50
  '@storm-software/linting-tools': ^1.132.67
  '@storm-software/markdownlint': ^0.30.66
  '@storm-software/prettier': ^0.57.66
  '@storm-software/testing-tools': ^1.119.66
  '@storm-software/tsconfig': ^0.47.66
  '@storm-software/tsdoc': ^0.13.66
  '@storm-software/untyped': ^0.24.48
  '@storm-software/workspace-tools': ^1.294.11
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.5
  '@swc/helpers': ^0.5.17
  '@swc/wasm': ^1.11.24
  '@taplo/cli': ^0.7.0
  '@types/jest': 30.0.0
  '@types/node': ^25.0.2
  '@types/pluralize': ^0.0.33
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/web': ^0.0.301
  chalk-template: ^1.1.2
  copyfiles: ^2.4.1
  defu: ^6.1.4
  esbuild: ^0.24.2
  eslint: ^9.39.2
  eslint-flat-config-utils: ^2.1.4
  imagemin: ^9.0.1
  imagemin-gifsicle: ^7.0.0
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-environment-node: ^30.2.0
  jest-util: 30.2.0
  jiti: ^2.4.2
  lefthook: ^2.0.12
  loader-utils: ^3.3.1
  log4brains: ^1.1.0
  nx: 22.2.5
  postcss: ^8.5.6
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  react-native: ^0.77.0
  remotion: ^4.0.390
  rimraf: ^6.1.2
  sharp: ^0.34.5
  sherif: ^1.9.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  ts-jest: 29.4.6
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.3.5
  tsx: ^4.21.0
  unbuild: ^3.3.1
  verdaccio: 6.2.4
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.4+sha512-Hegfb70ijqCc65CZwy8aLYhxrYQv3Wo+MZXqSfNAfcge7iSGYm2J3ydU5zkmf89JSvMOJy8J6lo/TMynBGvgtA==

fetchTimeout: 240000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines
  - '@earthquake/*'
  - earthquake

onlyBuiltDependencies:
  - '@swc/core'
  - aws-crt
  - core-js
  - esbuild
  - gifsicle
  - jpegtran-bin
  - lefthook
  - nx
  - optipng-bin
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@storm-software/tools-config': workspace:*
  '@storm-software/tools-scripts': workspace:*
  '@storm-software/video-assets': workspace:*
  cookie: '>=0.7.0'
  debug: '>=4.4.0'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.5'
  ip: '>=2.0.1'
  markdown-it: '>=14.1.0'
  micromatch: '>=4.0.8'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  path-to-regexp: '>=0.1.12'
  shell-quote: '>=1.8.2'
  simple-git: '>=3.27.0'
  zod: '>=4.0.5'

shamefullyHoist: true

trustPolicy: off

useNodeVersion: 24.11.1
